"""indexes_status_conferencia

Revision ID: 647feaacfd6b
Revises: 9fc1cd998997
Create Date: 2026-04-01 19:58:18.226603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647feaacfd6b'
down_revision = '9fc1cd998997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferencias', schema=None) as batch_op:
        batch_op.alter_column('status_resultado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('completo', 'incompleto', name='statusconferencia'),
               existing_nullable=True)
        batch_op.create_index('ix_conferencias_data', ['data_conferencia'], unique=False)
        batch_op.create_index('ix_conferencias_kit_id', ['kit_unidade_id'], unique=False)

    with op.batch_alter_table('kit_unidades', schema=None) as batch_op:
        batch_op.create_index('ix_kit_unidades_escola', ['escola'], unique=False)
        batch_op.create_index('ix_kit_unidades_status', ['status_atual'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kit_unidades', schema=None) as batch_op:
        batch_op.drop_index('ix_kit_unidades_status')
        batch_op.drop_index('ix_kit_unidades_escola')

    with op.batch_alter_table('conferencias', schema=None) as batch_op:
        batch_op.drop_index('ix_conferencias_kit_id')
        batch_op.drop_index('ix_conferencias_data')
        batch_op.alter_column('status_resultado',
               existing_type=sa.Enum('completo', 'incompleto', name='statusconferencia'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
