"""enums_role_status

Revision ID: 8dd9bfd25b6f
Revises: b7294dcecef8
Create Date: 2026-04-01 19:04:41.701795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd9bfd25b6f'
down_revision = 'b7294dcecef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_tokens')
    with op.batch_alter_table('kit_unidades', schema=None) as batch_op:
        batch_op.alter_column('status_atual',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('completo', 'incompleto', 'pendente', name='statuskit'),
               existing_nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('admin', 'pedagogo', 'auxiliar', name='role'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'pedagogo', 'auxiliar', name='role'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('kit_unidades', schema=None) as batch_op:
        batch_op.alter_column('status_atual',
               existing_type=sa.Enum('completo', 'incompleto', 'pendente', name='statuskit'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    op.create_table('api_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=80), nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('escola', sa.VARCHAR(length=200), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), nullable=True),
    sa.Column('ultimo_uso', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###
