"""Migração Inicial PostgreSQL

Revision ID: 9d90b7663bec
Revises: 
Create Date: 2026-04-05 15:11:49.920627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d90b7663bec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escolas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('kit_modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('foto_capa', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_lego', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_lego')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'pedagogo', 'auxiliar', name='role'), nullable=False),
    sa.Column('escola', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('nome_exibicao', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('composicao_kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_modelo_id', sa.Integer(), nullable=True),
    sa.Column('peca_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_esperada', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kit_modelo_id'], ['kit_modelos.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kit_unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificador', sa.String(length=50), nullable=False),
    sa.Column('kit_modelo_id', sa.Integer(), nullable=True),
    sa.Column('escola', sa.String(length=100), nullable=True),
    sa.Column('status_atual', sa.Enum('completo', 'incompleto', 'pendente', name='statuskit'), nullable=True),
    sa.ForeignKeyConstraint(['kit_modelo_id'], ['kit_modelos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kit_unidades', schema=None) as batch_op:
        batch_op.create_index('ix_kit_unidades_escola', ['escola'], unique=False)
        batch_op.create_index('ix_kit_unidades_status', ['status_atual'], unique=False)

    op.create_table('conferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_unidade_id', sa.Integer(), nullable=True),
    sa.Column('data_conferencia', sa.DateTime(), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status_resultado', sa.Enum('completo', 'incompleto', name='statusconferencia'), nullable=True),
    sa.ForeignKeyConstraint(['kit_unidade_id'], ['kit_unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conferencias', schema=None) as batch_op:
        batch_op.create_index('ix_conferencias_data', ['data_conferencia'], unique=False)
        batch_op.create_index('ix_conferencias_kit_id', ['kit_unidade_id'], unique=False)

    op.create_table('conferencia_detalhes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conferencia_id', sa.Integer(), nullable=True),
    sa.Column('peca_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_esperada_na_epoca', sa.Integer(), nullable=True),
    sa.Column('quantidade_encontrada', sa.Integer(), nullable=False),
    sa.Column('observacao_peca', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['conferencia_id'], ['conferencias.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conferencia_detalhes')
    with op.batch_alter_table('conferencias', schema=None) as batch_op:
        batch_op.drop_index('ix_conferencias_kit_id')
        batch_op.drop_index('ix_conferencias_data')

    op.drop_table('conferencias')
    with op.batch_alter_table('kit_unidades', schema=None) as batch_op:
        batch_op.drop_index('ix_kit_unidades_status')
        batch_op.drop_index('ix_kit_unidades_escola')

    op.drop_table('kit_unidades')
    op.drop_table('composicao_kits')
    op.drop_table('usuarios')
    op.drop_table('pecas')
    op.drop_table('kit_modelos')
    op.drop_table('escolas')
    # ### end Alembic commands ###
