"""email_nome_exibicao

Revision ID: 9fc1cd998997
Revises: 8dd9bfd25b6f
Create Date: 2026-04-01 19:50:32.355241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc1cd998997'
down_revision = '8dd9bfd25b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('nome_exibicao', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('nome_exibicao')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
